version: '2'

services:
  mongodb:
    container_name: mongodb
    image: 'bitnami/mongodb:6.0.3'
    networks:
      - backend
    ports:
      - "27017:27017"

  web_app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - mongodb
    container_name: web_app


networks:
  backend:
    driver: bridge
